# Clearmem2 operation RSA K-mean Clustering

In [1]:
import os
import numpy as np
import glob
import pandas as pd

In [19]:
operations = ['maintain', 'replace', 'suppress', 'clear']
n_operation = len(operations)
n_trials   = 12 #per run/ condition
n_runs     = 6
n_cells    = n_trials * n_runs * n_operation;
n_subjects = 2 #55
n_nodes    = 360 # per hemisphere

In [ ]:
## similarity matrix for each subjects
# 1. The RSA value is Fisher's z-transformation of Pearson's R
# 2. There are missing runs and trials for some subjects which have NaN values
#    And same trial is in the same cell location across subjects
# 3. The data is in subject space and some subjects do not have enough coverage for some nodes
#    So, the nodes which have less than 5 voxels were removed
# 4. Parcels_MNI is the reference parcellation in MNI space (1x1x1mm)

path = '/Users/Jacob/Dropbox/Jake/'
sm_vectors = {}
for xsubj in range(n_subjects):
    #print('(+) subject %.3d' % (xsubj+1))
    for xhemi in ['LH','RH']:
        # load smiliarity matrix
        xfiles = sorted(glob.glob(
            os.path.join(path, 'subj_sm', 'sub%.3d' % (xsubj+1), 
                         'sm_subj%.3d_%s_node*.csv' % (xsubj+1, xhemi))))
        for xf in xfiles:
            xsm = pd.read_csv(xf, header=None)
            xnode = xf.split('node')[1].split('.')[0]
            xvect = []
            for xx in range(n_cells-1):
                for yy in range(xx+1, n_cells):
                    xvect.append(xsm[xx][yy])
                    
            sm_vectors['sub%.3d_%s%s' % (xsubj+1, xhemi, xnode)] = xvect
            
            test = pd.DataFrame.from_dict(sm_vectors)
            test.to_csv('/Users/Jacob/Dropbox/Jake/sm_subj_%s.csv' % (xsubj+1))
            
            if xf == xfiles[0]:
                print(' - There are %d NaN cells in the similarity vector across nodes' % np.where(np.isnan(xvect))[0].shape[0])

 - There are 22992 NaN cells in the similarity vector across nodes
 - There are 22992 NaN cells in the similarity vector across nodes

In [4]:
test = pd.DataFrame.from_dict(sm_vectors)

In [32]:
test.tail()

,sub001_LH001,sub001_LH002,sub001_LH003,sub001_LH004,sub001_LH005,sub001_LH006,sub001_LH007,sub001_LH008,sub001_LH009,sub001_LH010,...,sub001_RH171,sub001_RH172,sub001_RH173,sub001_RH174,sub001_RH175,sub001_RH176,sub001_RH177,sub001_RH178,sub001_RH179,sub001_RH180
41323,0.102556,0.508242,-0.056194,0.048157,-0.321645,0.107923,-0.624669,-0.139116,-0.055085,-0.771813,...,-0.608593,-0.493647,-0.141341,-0.013759,0.248895,-0.790837,-0.684686,0.085875,-0.145079,-0.361754
41324,0.413451,0.298770,0.193916,0.397424,0.300631,0.410882,0.371114,0.078180,-0.182902,0.476703,...,0.380008,-0.554573,0.316360,-0.109126,0.232801,-0.097542,-0.476541,-0.074235,0.128859,-0.134363
41325,-0.000094,-0.221710,0.002631,0.688022,0.413598,-0.025423,0.325625,-0.000552,0.099248,-0.460279,...,-0.898166,1.048801,-0.882660,-0.557617,-0.158500,-0.564701,-0.282662,0.001992,0.158981,-0.015569
41326,0.549712,-0.365349,-0.096942,0.453807,-0.174872,0.068949,0.306226,-0.344019,-0.420142,0.532509,...,0.597690,0.270867,-0.072717,-0.668399,-0.141055,0.100355,-0.586869,-0.085145,-0.546150,-0.124679
41327,-0.053963,0.044072,-0.220050,0.310679,0.173927,0.236226,0.076123,0.135298,0.224189,-0.691609,...,-0.703603,-0.032474,-0.174262,0.231072,-0.258974,-0.101642,0.720550,0.137382,-0.058131,-0.115859

In [6]:
type(sm_vectors)

dict

In [ ]:
test.shape

In [7]:
test_na = test.dropna()

In [8]:
test_na

Empty DataFrame
Columns: [sub001_LH001, sub001_LH002, sub001_LH003, sub001_LH004, sub001_LH005, sub001_LH006, sub001_LH007, sub001_LH008, sub001_LH009, sub001_LH010, sub001_LH011, sub001_LH012, sub001_LH013, sub001_LH014, sub001_LH015, sub001_LH016, sub001_LH017, sub001_LH018, sub001_LH019, sub001_LH020, sub001_LH021, sub001_LH022, sub001_LH023, sub001_LH024, sub001_LH025, sub001_LH026, sub001_LH027, sub001_LH028, sub001_LH029, sub001_LH030, sub001_LH031, sub001_LH032, sub001_LH033, sub001_LH034, sub001_LH035, sub001_LH036, sub001_LH037, sub001_LH038, sub001_LH039, sub001_LH040, sub001_LH041, sub001_LH042, sub001_LH043, sub001_LH044, sub001_LH045, sub001_LH046, sub001_LH047, sub001_LH048, sub001_LH049, sub001_LH050, sub001_LH051, sub001_LH052, sub001_LH053, sub001_LH054, sub001_LH055, sub001_LH056, sub001_LH057, sub001_LH058, sub001_LH059, sub001_LH060, sub001_LH061, sub001_LH062, sub001_LH063, sub001_LH064, sub001_LH065, sub001_LH066, sub001_LH067, sub001_LH068, sub001_LH069, sub001_LH070, sub001_LH071, sub001_LH072, sub001_LH073, sub001_LH074, sub001_LH075, sub001_LH076, sub001_LH077, sub001_LH078, sub001_LH079, sub001_LH080, sub001_LH081, sub001_LH082, sub001_LH083, sub001_LH084, sub001_LH085, sub001_LH086, sub001_LH087, sub001_LH088, sub001_LH089, sub001_LH090, sub001_LH091, sub001_LH092, sub001_LH093, sub001_LH094, sub001_LH095, sub001_LH096, sub001_LH097, sub001_LH098, sub001_LH099, sub001_LH100, ...]
Index: []

[0 rows x 359 columns]

In [12]:
df_i = test.T
df_i.head()

,0,1,2,3,4,5,6,7,8,9,...,41318,41319,41320,41321,41322,41323,41324,41325,41326,41327
sub001_LH001,-0.442719,-0.386260,0.159651,0.260018,-0.520735,-0.274076,-0.357456,0.192775,-0.532891,-0.758266,...,0.085784,-0.030383,0.081461,-0.114450,0.218727,0.102556,0.413451,-0.000094,0.549712,-0.053963
sub001_LH002,0.066826,0.018281,-0.098232,0.336667,-0.111732,-0.258702,-0.013144,-0.068199,-0.036971,0.149817,...,0.302066,-0.406429,0.339721,-0.200965,-0.645527,0.508242,0.298770,-0.221710,-0.365349,0.044072
sub001_LH003,-1.060650,-1.232703,0.838105,-1.010863,-0.712869,-0.776790,0.555133,0.538614,0.179580,-0.557479,...,0.089440,-0.763215,-0.026000,0.303248,0.204999,-0.056194,0.193916,0.002631,-0.096942,-0.220050
sub001_LH004,-0.895593,-0.484895,0.206117,0.623622,-0.663430,-0.083433,-0.528064,0.332436,-0.646068,-0.649983,...,0.179608,-0.142903,-0.281637,0.006462,0.300884,0.048157,0.397424,0.688022,0.453807,0.310679
sub001_LH005,-0.736409,-0.604614,0.005191,0.156039,-0.646257,-0.086767,-0.453825,0.061901,-0.659365,-0.438503,...,0.480470,-0.284571,-0.102134,0.464247,-0.178199,-0.321645,0.300631,0.413598,-0.174872,0.173927

(0, 41328)